projects:
  coven:
    schemaPath: amplify/backend/api/coven/build/schema.graphql
    includes:
      - graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: graphql/typescript
        generatedFileName: API.ts
        docsFilePath: graphql
extensions:
  amplify:
    version: 3
